#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd &
xrdb /home/martin/.Xresources
feh --bg-fill /home/martin/Wallpapers/abs3.png
setxkbmap es &
#slstatus -s | lemonbar -f "Terminus-Bold" -B "#000000" -F "#88c0d0" &
xfce4-panel &
blueman-applet &
nm-applet &
xfce4-power-manager &
picom -D 0 &
#volumeicon &

bspc config border_width	1
bspc config window_gap		2
 
bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod4
 
bspc config automatic_scheme	spiral
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
